// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDuO1-1_WOWMKu273wi6yi2jFAhym04MTQ',
    appId: '1:709842396664:web:b0d89ed1835f24f62fe20d',
    messagingSenderId: '709842396664',
    projectId: 'campus-event-tracker-7e56e',
    authDomain: 'campus-event-tracker-7e56e.firebaseapp.com',
    storageBucket: 'campus-event-tracker-7e56e.firebasestorage.app',
    measurementId: 'G-LNL8JDVDPN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC1R9Se5tn1-bjjlf1XcOixaLtFspuvKDA',
    appId: '1:709842396664:android:4b86fffd03fed8152fe20d',
    messagingSenderId: '709842396664',
    projectId: 'campus-event-tracker-7e56e',
    storageBucket: 'campus-event-tracker-7e56e.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBVyp56XNww4NMjVxlNuFzzaMA992xaJhg',
    appId: '1:709842396664:ios:81aa355ded6878cb2fe20d',
    messagingSenderId: '709842396664',
    projectId: 'campus-event-tracker-7e56e',
    storageBucket: 'campus-event-tracker-7e56e.firebasestorage.app',
    iosBundleId: 'com.jimmy.campuseventtracker',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBVyp56XNww4NMjVxlNuFzzaMA992xaJhg',
    appId: '1:709842396664:ios:59210473a89b0deb2fe20d',
    messagingSenderId: '709842396664',
    projectId: 'campus-event-tracker-7e56e',
    storageBucket: 'campus-event-tracker-7e56e.firebasestorage.app',
    iosBundleId: 'com.example.campusEventTracker',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDuO1-1_WOWMKu273wi6yi2jFAhym04MTQ',
    appId: '1:709842396664:web:b4e5ac501a97fd382fe20d',
    messagingSenderId: '709842396664',
    projectId: 'campus-event-tracker-7e56e',
    authDomain: 'campus-event-tracker-7e56e.firebaseapp.com',
    storageBucket: 'campus-event-tracker-7e56e.firebasestorage.app',
    measurementId: 'G-DXPQ728Q8Q',
  );
}
