name: Flutter CI/CD Pipeline

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
      - name: Build APK
        run: |
          echo "${{ secrets.DOT_ENV }}" > .env
          flutter pub get
          flutter build apk --release
      - name: Write Firebase Service Account
        env:
          FIREBASE_CREDS: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_JSON }}
        run: echo "$FIREBASE_CREDS" > firebase-credentials.json
      - name: Upload to Firebase App Distribution
        uses: wzieba/Firebase-Distribution-Github-Action@v1
        with:
          appId: ${{ secrets.FIREBASE_APP_ID }}
          serviceCredentialsFile: firebase-credentials.json
          groups: testers
          file: build/app/outputs/flutter-apk/app-release.apk
